import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;

public class PathFinderApp {
    private JPanel mainPanel;
    private JComboBox comboBox1;
    private JComboBox comboBox2;
    private JTextArea dfs;
    private JButton calculateButton;
    private JTextArea field2;
    private JTextArea shortest;
    private Nation nation;

    public void results(JTextArea field, ShortestPathAlgorithms.Path path, double timeMs, String algorithmName) {
        StringBuilder sb = new StringBuilder();
        sb.append("Algorithm: ").append(algorithmName).append("\n");
        sb.append("─────────────────────────\n\n");

        if (path == null) {
            sb.append("Could not find road!\n");
            sb.append("There aren't any path between the cities.\n");
        } else {
            sb.append("Navigation:\n");
            City[] cities = path.getCities();
            for (int i = 0; i < cities.length; i++) {
                sb.append(cities[i].getName());
                if (i < cities.length - 1) {
                    sb.append(" → ");
                }
            }
            sb.append("\n\n");
            sb.append("Total distance: ").append(String.format("%.2f", path.getTotalDistance())).append(" km\n");
            sb.append("City count: ").append(cities.length).append("\n");
        }

        sb.append("\n");
        sb.append("Execute time: ").append(String.format("%.3f", timeMs)).append(" ms\n");
        sb.append("(").append(String.format("%.0f", timeMs * 1_000_000)).append(" ns)");

        field.setText(sb.toString());
    }

    public PathFinderApp() throws FileNotFoundException {
        nation = new Nation("Turkish_cities.csv");
        calculateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String startCity = comboBox1.getSelectedItem().toString();
                String destCity = comboBox2.getSelectedItem().toString();
                // Run DFS
                long start = System.nanoTime();
                ShortestPathAlgorithms.Path dfsPath = ShortestPathAlgorithms.dfs(nation, startCity, destCity);
                long end = System.nanoTime();
                double dfsTimeMs = (end - start) / 1_000_000.0;

                // Run DFS-Shortest
                start = System.nanoTime();
                ShortestPathAlgorithms.Path dfsShortestPath = ShortestPathAlgorithms.dfsShortest(nation, startCity, destCity);
                end = System.nanoTime();
                double dfsShortestTimeMs = (end - start) / 1_000_000.0;

                // Run Dijkstra
                start = System.nanoTime();
                ShortestPathAlgorithms.Path dijkstraPath = ShortestPathAlgorithms.dijkstra(nation, startCity, destCity);
                end = System.nanoTime();
                double dijkstraTimeMs = (end - start) / 1_000_000.0;
                results(dfs, dfsPath, dfsTimeMs, "DFS");
                results(shortest, dfsShortestPath, dfsShortestTimeMs, "DFS-Shortest");
                results(field2, dijkstraPath, dijkstraTimeMs, "Dijkstra");
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel3, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Turkish Cities Distance Calculator");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel1.add(label1, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel4, gbc);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Istanbul");
        defaultComboBoxModel1.addElement("Ankara");
        defaultComboBoxModel1.addElement("Izmir");
        defaultComboBoxModel1.addElement("Bursa");
        defaultComboBoxModel1.addElement("Adana");
        defaultComboBoxModel1.addElement("Gaziantep");
        defaultComboBoxModel1.addElement("Konya");
        defaultComboBoxModel1.addElement("Diyarbakir");
        defaultComboBoxModel1.addElement("Antalya");
        defaultComboBoxModel1.addElement("Mersin");
        defaultComboBoxModel1.addElement("Kayseri");
        defaultComboBoxModel1.addElement("Urfa");
        defaultComboBoxModel1.addElement("Malatya");
        defaultComboBoxModel1.addElement("Samsun");
        defaultComboBoxModel1.addElement("Denizli");
        defaultComboBoxModel1.addElement("Batman");
        defaultComboBoxModel1.addElement("Trabzon");
        comboBox1.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel4.add(comboBox1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("To");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.ipadx = 10;
        gbc.insets = new Insets(0, 10, 0, 10);
        panel4.add(label2, gbc);
        comboBox2 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("Istanbul");
        defaultComboBoxModel2.addElement("Ankara");
        defaultComboBoxModel2.addElement("Izmir");
        defaultComboBoxModel2.addElement("Bursa");
        defaultComboBoxModel2.addElement("Adana");
        defaultComboBoxModel2.addElement("Gaziantep");
        defaultComboBoxModel2.addElement("Konya");
        defaultComboBoxModel2.addElement("Diyarbakir");
        defaultComboBoxModel2.addElement("Antalya");
        defaultComboBoxModel2.addElement("Mersin");
        defaultComboBoxModel2.addElement("Kayseri");
        defaultComboBoxModel2.addElement("Urfa");
        defaultComboBoxModel2.addElement("Malatya");
        defaultComboBoxModel2.addElement("Samsun");
        defaultComboBoxModel2.addElement("Denizli");
        defaultComboBoxModel2.addElement("Batman");
        defaultComboBoxModel2.addElement("Trabzon");
        comboBox2.setModel(defaultComboBoxModel2);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel4.add(comboBox2, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 10);
        panel4.add(panel5, gbc);
        shortest = new JTextArea();
        shortest.setEditable(false);
        shortest.setLineWrap(false);
        shortest.setRows(10);
        shortest.setWrapStyleWord(true);
        panel5.add(shortest, BorderLayout.CENTER);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel4.add(panel6, gbc);
        dfs = new JTextArea();
        dfs.setEditable(false);
        dfs.setLineWrap(false);
        dfs.setRows(10);
        dfs.setWrapStyleWord(true);
        panel6.add(dfs, BorderLayout.CENTER);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel4.add(panel7, gbc);
        field2 = new JTextArea();
        field2.setEditable(false);
        field2.setLineWrap(false);
        field2.setRows(10);
        field2.setWrapStyleWord(true);
        panel7.add(field2, BorderLayout.CENTER);
        calculateButton = new JButton();
        calculateButton.setText("Calculate");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 15, 10);
        panel4.add(calculateButton, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("DFS");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel4.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Dijkstra");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        panel4.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("DF-Shortest");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        panel4.add(label5, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public static void main(String[] args) throws FileNotFoundException {
        JFrame frame = new JFrame("Path Finder");
        PathFinderApp app = new PathFinderApp();
        //frame.setSize(1200, 720);
        JComponent mainPanel = app.$$$getRootComponent$$$();
        mainPanel.setPreferredSize(new Dimension(600, 350));
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
